---
  - name: redis container
    docker:
      name: buffer
      image: redis
      command: redis-server --appendonly yes
      state: started
      expose:
        - 6379
      ports:
        - "6379:6379"
